-- compat.glad — OpenGL 4.1 Core Profile function loader.
-- Single-source C library, generated by glad for libigl.
-- EUI-NEO uses this to load OpenGL entry points at runtime.
--
-- All `mcpp` paths are GLOBS relative to the verdir; the leading `*/`
-- absorbs the GitHub tarball's `libigl-glad-<sha>/` wrap layer.
package = {
    spec        = "1",
    namespace   = "compat",
    name        = "glad",
    description = "OpenGL 4.1 Core Profile loader (libigl-glad fork)",
    licenses    = {"MIT"},
    repo        = "https://github.com/libigl/libigl-glad",
    type        = "package",

    xpm = {
        linux = {
            ["0.0.0-651a425"] = {
                url    = "https://github.com/libigl/libigl-glad/archive/651a425101365aa6e8504988ef9bb363d066c5ee.tar.gz",
                sha256 = "e144575e32f0b4bad311e5912ee4c7bed4f926d63359ae290bf34067c3dfb003",
            },
        },
        macosx = {
            ["0.0.0-651a425"] = {
                url    = "https://github.com/libigl/libigl-glad/archive/651a425101365aa6e8504988ef9bb363d066c5ee.tar.gz",
                sha256 = "e144575e32f0b4bad311e5912ee4c7bed4f926d63359ae290bf34067c3dfb003",
            },
        },
        windows = {
            ["0.0.0-651a425"] = {
                url    = "https://github.com/libigl/libigl-glad/archive/651a425101365aa6e8504988ef9bb363d066c5ee.tar.gz",
                sha256 = "e144575e32f0b4bad311e5912ee4c7bed4f926d63359ae290bf34067c3dfb003",
            },
        },
    },

    mcpp = {
        language     = "c++23",
        import_std   = false,
        c_standard   = "c99",
        include_dirs = { "*/include" },
        sources      = { "*/src/glad.c" },
        targets      = { ["glad"] = { kind = "lib" } },
        deps         = {},
        linux        = { ldflags = { "-ldl" } },
        macosx       = { ldflags = { "-ldl" } },
    },
}
